name: Write Terraform Plan to Pull Request

on:
  pull_request:
    branches:
      - main  # or any other branch you want to trigger the deployment

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    defaults:
      run:
        working-directory: terraform
    permissions:
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2 

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.3 

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Plan
      uses: dflook/terraform-plan@v1
