name: Deploy IAM Resources to AWS with Terraform

on:
  pull_request:
    branches:
      - main  # or any other branch you want to trigger the deployment

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0 # Specify the Terraform version

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2 # Change to your AWS region

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    # - name: Terraform Plan
    #   uses: dflook/terraform-plan@v1
    #   with:
    #     path: terraform


